# fly.toml app configuration file generated for challenger-scouting on 2026-05-01T03:04:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'challenger-scouting'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  PLATFORM = 'euw1'
  PORT = '8000'
  REGION = 'europe'

[[mounts]]
  source = 'scouting_data'
  destination = '/app/backend/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'get'
    path = '/api/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
